name: robotkernel
channels:
  - conda-forge
dependencies:
  - python >=3.6,<3.8.0a0
  - jupyterlab >=1.2.4,<1.3
  - nodejs >=11,<12
  - pip
  - pip:
    - robotframework==3.1.2
    - robotkernel==1.3.0
    - jupytext==1.3.2
