#!/bin/bash
python -m robotkernel.install --sys-prefix
jupyter nbextension install --py jupytext --sys-prefix
jupyter nbextension enable --py jupytext --sys-prefix
jupyter serverextension enable jupytext
jupyter labextension install jupyterlab_robotmode --no-build
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install jupyterlab-jupytext --no-build
jupyter lab build --minimize=True --dev-build=False --debug
mkdir -p .jupyter
mkdir -p .ipython/profile_default/static/custom/
cp binder/jupyter_notebook_config.py .jupyter
cp binder/custom.css .ipython/profile_default/static/custom/
cp binder/iframeResizer.contentWindow.min.js .ipython/profile_default/static/custom/custom.js
